/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as RegulationsRouteImport } from './routes/regulations'
import { Route as RequestNotificationsRouteImport } from './routes/request-notifications'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as VacationsRouteImport } from './routes/vacations'
import { Route as RegulationsIndexRouteImport } from './routes/regulations.index'
import { Route as RegulationsApprovalsRouteImport } from './routes/regulations.approvals'
import { Route as RegulationsBankFeesRouteImport } from './routes/regulations.bank-fees'
import { Route as RegulationsDeductionsRouteImport } from './routes/regulations.deductions'
import { Route as RegulationsEosRouteImport } from './routes/regulations.eos'
import { Route as RegulationsFingerprintRouteImport } from './routes/regulations.fingerprint'
import { Route as RegulationsLoansRouteImport } from './routes/regulations.loans'
import { Route as RegulationsOtherRouteImport } from './routes/regulations.other'
import { Route as RegulationsPermitsRouteImport } from './routes/regulations.permits'
import { Route as RegulationsShiftsRouteImport } from './routes/regulations.shifts'
import { Route as RegulationsVacationsRouteImport } from './routes/regulations.vacations'
import { Route as SettingsBasicRouteImport } from './routes/settings.basic'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffAddRouteImport } from './routes/staff.add'
import { Route as StaffBankBlockRouteImport } from './routes/staff.bank-block'
import { Route as StaffContractsRouteImport } from './routes/staff.contracts'
import { Route as StaffManagerRouteImport } from './routes/staff.manager'
import { Route as StaffTransferRouteImport } from './routes/staff.transfer'
import { Route as StaffUpdateRouteImport } from './routes/staff.update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsRoute = RegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNotificationsRoute = RequestNotificationsRouteImport.update({
  id: '/request-notifications',
  path: '/request-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationsRoute = VacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsIndexRoute = RegulationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsApprovalsRoute = RegulationsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsBankFeesRoute = RegulationsBankFeesRouteImport.update({
  id: '/bank-fees',
  path: '/bank-fees',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsDeductionsRoute = RegulationsDeductionsRouteImport.update({
  id: '/deductions',
  path: '/deductions',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsEosRoute = RegulationsEosRouteImport.update({
  id: '/eos',
  path: '/eos',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsFingerprintRoute = RegulationsFingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsLoansRoute = RegulationsLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsOtherRoute = RegulationsOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsPermitsRoute = RegulationsPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsShiftsRoute = RegulationsShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsVacationsRoute = RegulationsVacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => RegulationsRoute,
} as any)
const SettingsBasicRoute = SettingsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAddRoute = StaffAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBankBlockRoute = StaffBankBlockRouteImport.update({
  id: '/bank-block',
  path: '/bank-block',
  getParentRoute: () => StaffRoute,
} as any)
const StaffContractsRoute = StaffContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffManagerRoute = StaffManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTransferRoute = StaffTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUpdateRoute = StaffUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRoute
  '/regulations': typeof RegulationsRouteWithChildren
  '/request-notifications': typeof RequestNotificationsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/regulations/': typeof RegulationsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRoute
  '/request-notifications': typeof RequestNotificationsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/regulations': typeof RegulationsIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRoute
  '/regulations': typeof RegulationsRouteWithChildren
  '/request-notifications': typeof RequestNotificationsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/regulations/': typeof RegulationsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/regulations'
    | '/request-notifications'
    | '/settings'
    | '/staff'
    | '/surveys'
    | '/vacations'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/settings/basic'
    | '/settings/general'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/regulations/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/request-notifications'
    | '/settings'
    | '/surveys'
    | '/vacations'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/settings/basic'
    | '/settings/general'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/regulations'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/regulations'
    | '/request-notifications'
    | '/settings'
    | '/staff'
    | '/surveys'
    | '/vacations'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/settings/basic'
    | '/settings/general'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/regulations/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InquiriesRoute: typeof InquiriesRoute
  LeavesRoute: typeof LeavesRoute
  LoansRoute: typeof LoansRoute
  PayrollRoute: typeof PayrollRoute
  RegulationsRoute: typeof RegulationsRouteWithChildren
  RequestNotificationsRoute: typeof RequestNotificationsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  SurveysRoute: typeof SurveysRoute
  VacationsRoute: typeof VacationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations': {
      id: '/regulations'
      path: '/regulations'
      fullPath: '/regulations'
      preLoaderRoute: typeof RegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-notifications': {
      id: '/request-notifications'
      path: '/request-notifications'
      fullPath: '/request-notifications'
      preLoaderRoute: typeof RequestNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacations': {
      id: '/vacations'
      path: '/vacations'
      fullPath: '/vacations'
      preLoaderRoute: typeof VacationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations/': {
      id: '/regulations/'
      path: '/'
      fullPath: '/regulations/'
      preLoaderRoute: typeof RegulationsIndexRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/approvals': {
      id: '/regulations/approvals'
      path: '/approvals'
      fullPath: '/regulations/approvals'
      preLoaderRoute: typeof RegulationsApprovalsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/bank-fees': {
      id: '/regulations/bank-fees'
      path: '/bank-fees'
      fullPath: '/regulations/bank-fees'
      preLoaderRoute: typeof RegulationsBankFeesRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/deductions': {
      id: '/regulations/deductions'
      path: '/deductions'
      fullPath: '/regulations/deductions'
      preLoaderRoute: typeof RegulationsDeductionsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/eos': {
      id: '/regulations/eos'
      path: '/eos'
      fullPath: '/regulations/eos'
      preLoaderRoute: typeof RegulationsEosRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/fingerprint': {
      id: '/regulations/fingerprint'
      path: '/fingerprint'
      fullPath: '/regulations/fingerprint'
      preLoaderRoute: typeof RegulationsFingerprintRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/loans': {
      id: '/regulations/loans'
      path: '/loans'
      fullPath: '/regulations/loans'
      preLoaderRoute: typeof RegulationsLoansRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/other': {
      id: '/regulations/other'
      path: '/other'
      fullPath: '/regulations/other'
      preLoaderRoute: typeof RegulationsOtherRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/permits': {
      id: '/regulations/permits'
      path: '/permits'
      fullPath: '/regulations/permits'
      preLoaderRoute: typeof RegulationsPermitsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/shifts': {
      id: '/regulations/shifts'
      path: '/shifts'
      fullPath: '/regulations/shifts'
      preLoaderRoute: typeof RegulationsShiftsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/vacations': {
      id: '/regulations/vacations'
      path: '/vacations'
      fullPath: '/regulations/vacations'
      preLoaderRoute: typeof RegulationsVacationsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/settings/basic': {
      id: '/settings/basic'
      path: '/basic'
      fullPath: '/settings/basic'
      preLoaderRoute: typeof SettingsBasicRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/add': {
      id: '/staff/add'
      path: '/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof StaffAddRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/bank-block': {
      id: '/staff/bank-block'
      path: '/bank-block'
      fullPath: '/staff/bank-block'
      preLoaderRoute: typeof StaffBankBlockRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/contracts': {
      id: '/staff/contracts'
      path: '/contracts'
      fullPath: '/staff/contracts'
      preLoaderRoute: typeof StaffContractsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/manager': {
      id: '/staff/manager'
      path: '/manager'
      fullPath: '/staff/manager'
      preLoaderRoute: typeof StaffManagerRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/transfer': {
      id: '/staff/transfer'
      path: '/transfer'
      fullPath: '/staff/transfer'
      preLoaderRoute: typeof StaffTransferRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/update': {
      id: '/staff/update'
      path: '/update'
      fullPath: '/staff/update'
      preLoaderRoute: typeof StaffUpdateRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface RegulationsRouteChildren {
  RegulationsApprovalsRoute: typeof RegulationsApprovalsRoute
  RegulationsBankFeesRoute: typeof RegulationsBankFeesRoute
  RegulationsDeductionsRoute: typeof RegulationsDeductionsRoute
  RegulationsEosRoute: typeof RegulationsEosRoute
  RegulationsFingerprintRoute: typeof RegulationsFingerprintRoute
  RegulationsLoansRoute: typeof RegulationsLoansRoute
  RegulationsOtherRoute: typeof RegulationsOtherRoute
  RegulationsPermitsRoute: typeof RegulationsPermitsRoute
  RegulationsShiftsRoute: typeof RegulationsShiftsRoute
  RegulationsVacationsRoute: typeof RegulationsVacationsRoute
  RegulationsIndexRoute: typeof RegulationsIndexRoute
}

const RegulationsRouteChildren: RegulationsRouteChildren = {
  RegulationsApprovalsRoute: RegulationsApprovalsRoute,
  RegulationsBankFeesRoute: RegulationsBankFeesRoute,
  RegulationsDeductionsRoute: RegulationsDeductionsRoute,
  RegulationsEosRoute: RegulationsEosRoute,
  RegulationsFingerprintRoute: RegulationsFingerprintRoute,
  RegulationsLoansRoute: RegulationsLoansRoute,
  RegulationsOtherRoute: RegulationsOtherRoute,
  RegulationsPermitsRoute: RegulationsPermitsRoute,
  RegulationsShiftsRoute: RegulationsShiftsRoute,
  RegulationsVacationsRoute: RegulationsVacationsRoute,
  RegulationsIndexRoute: RegulationsIndexRoute,
}

const RegulationsRouteWithChildren = RegulationsRoute._addFileChildren(
  RegulationsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsBasicRoute: typeof SettingsBasicRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBasicRoute: SettingsBasicRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StaffRouteChildren {
  StaffAddRoute: typeof StaffAddRoute
  StaffBankBlockRoute: typeof StaffBankBlockRoute
  StaffContractsRoute: typeof StaffContractsRoute
  StaffManagerRoute: typeof StaffManagerRoute
  StaffTransferRoute: typeof StaffTransferRoute
  StaffUpdateRoute: typeof StaffUpdateRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAddRoute: StaffAddRoute,
  StaffBankBlockRoute: StaffBankBlockRoute,
  StaffContractsRoute: StaffContractsRoute,
  StaffManagerRoute: StaffManagerRoute,
  StaffTransferRoute: StaffTransferRoute,
  StaffUpdateRoute: StaffUpdateRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InquiriesRoute: InquiriesRoute,
  LeavesRoute: LeavesRoute,
  LoansRoute: LoansRoute,
  PayrollRoute: PayrollRoute,
  RegulationsRoute: RegulationsRouteWithChildren,
  RequestNotificationsRoute: RequestNotificationsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  SurveysRoute: SurveysRoute,
  VacationsRoute: VacationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
