/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalRequestsRouteImport } from './routes/approval-requests'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CorrespondenceRouteImport } from './routes/correspondence'
import { Route as EndOfServiceProvisionRouteImport } from './routes/end-of-service-provision'
import { Route as EndOfServiceRequestsRouteImport } from './routes/end-of-service-requests'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PermitsRouteImport } from './routes/permits'
import { Route as RegulationsRouteImport } from './routes/regulations'
import { Route as RequestNotificationsRouteImport } from './routes/request-notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as VacationsRouteImport } from './routes/vacations'
import { Route as RegulationsIndexRouteImport } from './routes/regulations.index'
import { Route as RegulationsApprovalsRouteImport } from './routes/regulations.approvals'
import { Route as RegulationsBankFeesRouteImport } from './routes/regulations.bank-fees'
import { Route as RegulationsDeductionsRouteImport } from './routes/regulations.deductions'
import { Route as RegulationsEosRouteImport } from './routes/regulations.eos'
import { Route as RegulationsFingerprintRouteImport } from './routes/regulations.fingerprint'
import { Route as RegulationsLoansRouteImport } from './routes/regulations.loans'
import { Route as RegulationsOtherRouteImport } from './routes/regulations.other'
import { Route as RegulationsPermitsRouteImport } from './routes/regulations.permits'
import { Route as RegulationsShiftsRouteImport } from './routes/regulations.shifts'
import { Route as RegulationsVacationsRouteImport } from './routes/regulations.vacations'
import { Route as ReportsAttendanceRouteImport } from './routes/reports.attendance'
import { Route as ReportsFingerprintRouteImport } from './routes/reports.fingerprint'
import { Route as SettingsAccountLinksRouteImport } from './routes/settings.account-links'
import { Route as SettingsBasicRouteImport } from './routes/settings.basic'
import { Route as SettingsCalendarRouteImport } from './routes/settings.calendar'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffAddRouteImport } from './routes/staff.add'
import { Route as StaffBankBlockRouteImport } from './routes/staff.bank-block'
import { Route as StaffContractsRouteImport } from './routes/staff.contracts'
import { Route as StaffManagerRouteImport } from './routes/staff.manager'
import { Route as StaffTransferRouteImport } from './routes/staff.transfer'
import { Route as StaffUpdateRouteImport } from './routes/staff.update'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksPermissionsRouteImport } from './routes/tasks.permissions'
import { Route as TasksReportsRouteImport } from './routes/tasks.reports'
import { Route as TasksSetupRouteImport } from './routes/tasks.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRequestsRoute = ApprovalRequestsRouteImport.update({
  id: '/approval-requests',
  path: '/approval-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenceRoute = CorrespondenceRouteImport.update({
  id: '/correspondence',
  path: '/correspondence',
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfServiceProvisionRoute = EndOfServiceProvisionRouteImport.update({
  id: '/end-of-service-provision',
  path: '/end-of-service-provision',
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfServiceRequestsRoute = EndOfServiceRequestsRouteImport.update({
  id: '/end-of-service-requests',
  path: '/end-of-service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsRoute = PermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsRoute = RegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNotificationsRoute = RequestNotificationsRouteImport.update({
  id: '/request-notifications',
  path: '/request-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationsRoute = VacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsIndexRoute = RegulationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsApprovalsRoute = RegulationsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsBankFeesRoute = RegulationsBankFeesRouteImport.update({
  id: '/bank-fees',
  path: '/bank-fees',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsDeductionsRoute = RegulationsDeductionsRouteImport.update({
  id: '/deductions',
  path: '/deductions',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsEosRoute = RegulationsEosRouteImport.update({
  id: '/eos',
  path: '/eos',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsFingerprintRoute = RegulationsFingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsLoansRoute = RegulationsLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsOtherRoute = RegulationsOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsPermitsRoute = RegulationsPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsShiftsRoute = RegulationsShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => RegulationsRoute,
} as any)
const RegulationsVacationsRoute = RegulationsVacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => RegulationsRoute,
} as any)
const ReportsAttendanceRoute = ReportsAttendanceRouteImport.update({
  id: '/reports/attendance',
  path: '/reports/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFingerprintRoute = ReportsFingerprintRouteImport.update({
  id: '/reports/fingerprint',
  path: '/reports/fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountLinksRoute = SettingsAccountLinksRouteImport.update({
  id: '/account-links',
  path: '/account-links',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBasicRoute = SettingsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCalendarRoute = SettingsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAddRoute = StaffAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBankBlockRoute = StaffBankBlockRouteImport.update({
  id: '/bank-block',
  path: '/bank-block',
  getParentRoute: () => StaffRoute,
} as any)
const StaffContractsRoute = StaffContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffManagerRoute = StaffManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTransferRoute = StaffTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUpdateRoute = StaffUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => StaffRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksPermissionsRoute = TasksPermissionsRouteImport.update({
  id: '/tasks/permissions',
  path: '/tasks/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksReportsRoute = TasksReportsRouteImport.update({
  id: '/tasks/reports',
  path: '/tasks/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSetupRoute = TasksSetupRouteImport.update({
  id: '/tasks/setup',
  path: '/tasks/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval-requests': typeof ApprovalRequestsRoute
  '/auth': typeof AuthRoute
  '/correspondence': typeof CorrespondenceRoute
  '/end-of-service-provision': typeof EndOfServiceProvisionRoute
  '/end-of-service-requests': typeof EndOfServiceRequestsRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRoute
  '/permits': typeof PermitsRoute
  '/regulations': typeof RegulationsRouteWithChildren
  '/request-notifications': typeof RequestNotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fingerprint': typeof ReportsFingerprintRoute
  '/settings/account-links': typeof SettingsAccountLinksRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/tasks/permissions': typeof TasksPermissionsRoute
  '/tasks/reports': typeof TasksReportsRoute
  '/tasks/setup': typeof TasksSetupRoute
  '/regulations/': typeof RegulationsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval-requests': typeof ApprovalRequestsRoute
  '/auth': typeof AuthRoute
  '/correspondence': typeof CorrespondenceRoute
  '/end-of-service-provision': typeof EndOfServiceProvisionRoute
  '/end-of-service-requests': typeof EndOfServiceRequestsRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRoute
  '/permits': typeof PermitsRoute
  '/request-notifications': typeof RequestNotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fingerprint': typeof ReportsFingerprintRoute
  '/settings/account-links': typeof SettingsAccountLinksRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/tasks/permissions': typeof TasksPermissionsRoute
  '/tasks/reports': typeof TasksReportsRoute
  '/tasks/setup': typeof TasksSetupRoute
  '/regulations': typeof RegulationsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval-requests': typeof ApprovalRequestsRoute
  '/auth': typeof AuthRoute
  '/correspondence': typeof CorrespondenceRoute
  '/end-of-service-provision': typeof EndOfServiceProvisionRoute
  '/end-of-service-requests': typeof EndOfServiceRequestsRoute
  '/inquiries': typeof InquiriesRoute
  '/leaves': typeof LeavesRoute
  '/loans': typeof LoansRoute
  '/payroll': typeof PayrollRoute
  '/permits': typeof PermitsRoute
  '/regulations': typeof RegulationsRouteWithChildren
  '/request-notifications': typeof RequestNotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/surveys': typeof SurveysRoute
  '/vacations': typeof VacationsRoute
  '/regulations/approvals': typeof RegulationsApprovalsRoute
  '/regulations/bank-fees': typeof RegulationsBankFeesRoute
  '/regulations/deductions': typeof RegulationsDeductionsRoute
  '/regulations/eos': typeof RegulationsEosRoute
  '/regulations/fingerprint': typeof RegulationsFingerprintRoute
  '/regulations/loans': typeof RegulationsLoansRoute
  '/regulations/other': typeof RegulationsOtherRoute
  '/regulations/permits': typeof RegulationsPermitsRoute
  '/regulations/shifts': typeof RegulationsShiftsRoute
  '/regulations/vacations': typeof RegulationsVacationsRoute
  '/reports/attendance': typeof ReportsAttendanceRoute
  '/reports/fingerprint': typeof ReportsFingerprintRoute
  '/settings/account-links': typeof SettingsAccountLinksRoute
  '/settings/basic': typeof SettingsBasicRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/staff/add': typeof StaffAddRoute
  '/staff/bank-block': typeof StaffBankBlockRoute
  '/staff/contracts': typeof StaffContractsRoute
  '/staff/manager': typeof StaffManagerRoute
  '/staff/transfer': typeof StaffTransferRoute
  '/staff/update': typeof StaffUpdateRoute
  '/tasks/permissions': typeof TasksPermissionsRoute
  '/tasks/reports': typeof TasksReportsRoute
  '/tasks/setup': typeof TasksSetupRoute
  '/regulations/': typeof RegulationsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approval-requests'
    | '/auth'
    | '/correspondence'
    | '/end-of-service-provision'
    | '/end-of-service-requests'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/permits'
    | '/regulations'
    | '/request-notifications'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/surveys'
    | '/vacations'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/reports/attendance'
    | '/reports/fingerprint'
    | '/settings/account-links'
    | '/settings/basic'
    | '/settings/calendar'
    | '/settings/general'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/tasks/permissions'
    | '/tasks/reports'
    | '/tasks/setup'
    | '/regulations/'
    | '/staff/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approval-requests'
    | '/auth'
    | '/correspondence'
    | '/end-of-service-provision'
    | '/end-of-service-requests'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/permits'
    | '/request-notifications'
    | '/reset-password'
    | '/settings'
    | '/surveys'
    | '/vacations'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/reports/attendance'
    | '/reports/fingerprint'
    | '/settings/account-links'
    | '/settings/basic'
    | '/settings/calendar'
    | '/settings/general'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/tasks/permissions'
    | '/tasks/reports'
    | '/tasks/setup'
    | '/regulations'
    | '/staff'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/approval-requests'
    | '/auth'
    | '/correspondence'
    | '/end-of-service-provision'
    | '/end-of-service-requests'
    | '/inquiries'
    | '/leaves'
    | '/loans'
    | '/payroll'
    | '/permits'
    | '/regulations'
    | '/request-notifications'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/surveys'
    | '/vacations'
    | '/regulations/approvals'
    | '/regulations/bank-fees'
    | '/regulations/deductions'
    | '/regulations/eos'
    | '/regulations/fingerprint'
    | '/regulations/loans'
    | '/regulations/other'
    | '/regulations/permits'
    | '/regulations/shifts'
    | '/regulations/vacations'
    | '/reports/attendance'
    | '/reports/fingerprint'
    | '/settings/account-links'
    | '/settings/basic'
    | '/settings/calendar'
    | '/settings/general'
    | '/staff/add'
    | '/staff/bank-block'
    | '/staff/contracts'
    | '/staff/manager'
    | '/staff/transfer'
    | '/staff/update'
    | '/tasks/permissions'
    | '/tasks/reports'
    | '/tasks/setup'
    | '/regulations/'
    | '/staff/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalRequestsRoute: typeof ApprovalRequestsRoute
  AuthRoute: typeof AuthRoute
  CorrespondenceRoute: typeof CorrespondenceRoute
  EndOfServiceProvisionRoute: typeof EndOfServiceProvisionRoute
  EndOfServiceRequestsRoute: typeof EndOfServiceRequestsRoute
  InquiriesRoute: typeof InquiriesRoute
  LeavesRoute: typeof LeavesRoute
  LoansRoute: typeof LoansRoute
  PayrollRoute: typeof PayrollRoute
  PermitsRoute: typeof PermitsRoute
  RegulationsRoute: typeof RegulationsRouteWithChildren
  RequestNotificationsRoute: typeof RequestNotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  SurveysRoute: typeof SurveysRoute
  VacationsRoute: typeof VacationsRoute
  ReportsAttendanceRoute: typeof ReportsAttendanceRoute
  ReportsFingerprintRoute: typeof ReportsFingerprintRoute
  TasksPermissionsRoute: typeof TasksPermissionsRoute
  TasksReportsRoute: typeof TasksReportsRoute
  TasksSetupRoute: typeof TasksSetupRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-requests': {
      id: '/approval-requests'
      path: '/approval-requests'
      fullPath: '/approval-requests'
      preLoaderRoute: typeof ApprovalRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence': {
      id: '/correspondence'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof CorrespondenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-of-service-provision': {
      id: '/end-of-service-provision'
      path: '/end-of-service-provision'
      fullPath: '/end-of-service-provision'
      preLoaderRoute: typeof EndOfServiceProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-of-service-requests': {
      id: '/end-of-service-requests'
      path: '/end-of-service-requests'
      fullPath: '/end-of-service-requests'
      preLoaderRoute: typeof EndOfServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits': {
      id: '/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof PermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations': {
      id: '/regulations'
      path: '/regulations'
      fullPath: '/regulations'
      preLoaderRoute: typeof RegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-notifications': {
      id: '/request-notifications'
      path: '/request-notifications'
      fullPath: '/request-notifications'
      preLoaderRoute: typeof RequestNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacations': {
      id: '/vacations'
      path: '/vacations'
      fullPath: '/vacations'
      preLoaderRoute: typeof VacationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations/': {
      id: '/regulations/'
      path: '/'
      fullPath: '/regulations/'
      preLoaderRoute: typeof RegulationsIndexRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/approvals': {
      id: '/regulations/approvals'
      path: '/approvals'
      fullPath: '/regulations/approvals'
      preLoaderRoute: typeof RegulationsApprovalsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/bank-fees': {
      id: '/regulations/bank-fees'
      path: '/bank-fees'
      fullPath: '/regulations/bank-fees'
      preLoaderRoute: typeof RegulationsBankFeesRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/deductions': {
      id: '/regulations/deductions'
      path: '/deductions'
      fullPath: '/regulations/deductions'
      preLoaderRoute: typeof RegulationsDeductionsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/eos': {
      id: '/regulations/eos'
      path: '/eos'
      fullPath: '/regulations/eos'
      preLoaderRoute: typeof RegulationsEosRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/fingerprint': {
      id: '/regulations/fingerprint'
      path: '/fingerprint'
      fullPath: '/regulations/fingerprint'
      preLoaderRoute: typeof RegulationsFingerprintRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/loans': {
      id: '/regulations/loans'
      path: '/loans'
      fullPath: '/regulations/loans'
      preLoaderRoute: typeof RegulationsLoansRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/other': {
      id: '/regulations/other'
      path: '/other'
      fullPath: '/regulations/other'
      preLoaderRoute: typeof RegulationsOtherRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/permits': {
      id: '/regulations/permits'
      path: '/permits'
      fullPath: '/regulations/permits'
      preLoaderRoute: typeof RegulationsPermitsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/shifts': {
      id: '/regulations/shifts'
      path: '/shifts'
      fullPath: '/regulations/shifts'
      preLoaderRoute: typeof RegulationsShiftsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/regulations/vacations': {
      id: '/regulations/vacations'
      path: '/vacations'
      fullPath: '/regulations/vacations'
      preLoaderRoute: typeof RegulationsVacationsRouteImport
      parentRoute: typeof RegulationsRoute
    }
    '/reports/attendance': {
      id: '/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof ReportsAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/fingerprint': {
      id: '/reports/fingerprint'
      path: '/reports/fingerprint'
      fullPath: '/reports/fingerprint'
      preLoaderRoute: typeof ReportsFingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account-links': {
      id: '/settings/account-links'
      path: '/account-links'
      fullPath: '/settings/account-links'
      preLoaderRoute: typeof SettingsAccountLinksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/basic': {
      id: '/settings/basic'
      path: '/basic'
      fullPath: '/settings/basic'
      preLoaderRoute: typeof SettingsBasicRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/calendar': {
      id: '/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof SettingsCalendarRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/add': {
      id: '/staff/add'
      path: '/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof StaffAddRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/bank-block': {
      id: '/staff/bank-block'
      path: '/bank-block'
      fullPath: '/staff/bank-block'
      preLoaderRoute: typeof StaffBankBlockRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/contracts': {
      id: '/staff/contracts'
      path: '/contracts'
      fullPath: '/staff/contracts'
      preLoaderRoute: typeof StaffContractsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/manager': {
      id: '/staff/manager'
      path: '/manager'
      fullPath: '/staff/manager'
      preLoaderRoute: typeof StaffManagerRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/transfer': {
      id: '/staff/transfer'
      path: '/transfer'
      fullPath: '/staff/transfer'
      preLoaderRoute: typeof StaffTransferRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/update': {
      id: '/staff/update'
      path: '/update'
      fullPath: '/staff/update'
      preLoaderRoute: typeof StaffUpdateRouteImport
      parentRoute: typeof StaffRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/permissions': {
      id: '/tasks/permissions'
      path: '/tasks/permissions'
      fullPath: '/tasks/permissions'
      preLoaderRoute: typeof TasksPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/reports': {
      id: '/tasks/reports'
      path: '/tasks/reports'
      fullPath: '/tasks/reports'
      preLoaderRoute: typeof TasksReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/setup': {
      id: '/tasks/setup'
      path: '/tasks/setup'
      fullPath: '/tasks/setup'
      preLoaderRoute: typeof TasksSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegulationsRouteChildren {
  RegulationsApprovalsRoute: typeof RegulationsApprovalsRoute
  RegulationsBankFeesRoute: typeof RegulationsBankFeesRoute
  RegulationsDeductionsRoute: typeof RegulationsDeductionsRoute
  RegulationsEosRoute: typeof RegulationsEosRoute
  RegulationsFingerprintRoute: typeof RegulationsFingerprintRoute
  RegulationsLoansRoute: typeof RegulationsLoansRoute
  RegulationsOtherRoute: typeof RegulationsOtherRoute
  RegulationsPermitsRoute: typeof RegulationsPermitsRoute
  RegulationsShiftsRoute: typeof RegulationsShiftsRoute
  RegulationsVacationsRoute: typeof RegulationsVacationsRoute
  RegulationsIndexRoute: typeof RegulationsIndexRoute
}

const RegulationsRouteChildren: RegulationsRouteChildren = {
  RegulationsApprovalsRoute: RegulationsApprovalsRoute,
  RegulationsBankFeesRoute: RegulationsBankFeesRoute,
  RegulationsDeductionsRoute: RegulationsDeductionsRoute,
  RegulationsEosRoute: RegulationsEosRoute,
  RegulationsFingerprintRoute: RegulationsFingerprintRoute,
  RegulationsLoansRoute: RegulationsLoansRoute,
  RegulationsOtherRoute: RegulationsOtherRoute,
  RegulationsPermitsRoute: RegulationsPermitsRoute,
  RegulationsShiftsRoute: RegulationsShiftsRoute,
  RegulationsVacationsRoute: RegulationsVacationsRoute,
  RegulationsIndexRoute: RegulationsIndexRoute,
}

const RegulationsRouteWithChildren = RegulationsRoute._addFileChildren(
  RegulationsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountLinksRoute: typeof SettingsAccountLinksRoute
  SettingsBasicRoute: typeof SettingsBasicRoute
  SettingsCalendarRoute: typeof SettingsCalendarRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountLinksRoute: SettingsAccountLinksRoute,
  SettingsBasicRoute: SettingsBasicRoute,
  SettingsCalendarRoute: SettingsCalendarRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StaffRouteChildren {
  StaffAddRoute: typeof StaffAddRoute
  StaffBankBlockRoute: typeof StaffBankBlockRoute
  StaffContractsRoute: typeof StaffContractsRoute
  StaffManagerRoute: typeof StaffManagerRoute
  StaffTransferRoute: typeof StaffTransferRoute
  StaffUpdateRoute: typeof StaffUpdateRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAddRoute: StaffAddRoute,
  StaffBankBlockRoute: StaffBankBlockRoute,
  StaffContractsRoute: StaffContractsRoute,
  StaffManagerRoute: StaffManagerRoute,
  StaffTransferRoute: StaffTransferRoute,
  StaffUpdateRoute: StaffUpdateRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalRequestsRoute: ApprovalRequestsRoute,
  AuthRoute: AuthRoute,
  CorrespondenceRoute: CorrespondenceRoute,
  EndOfServiceProvisionRoute: EndOfServiceProvisionRoute,
  EndOfServiceRequestsRoute: EndOfServiceRequestsRoute,
  InquiriesRoute: InquiriesRoute,
  LeavesRoute: LeavesRoute,
  LoansRoute: LoansRoute,
  PayrollRoute: PayrollRoute,
  PermitsRoute: PermitsRoute,
  RegulationsRoute: RegulationsRouteWithChildren,
  RequestNotificationsRoute: RequestNotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  SurveysRoute: SurveysRoute,
  VacationsRoute: VacationsRoute,
  ReportsAttendanceRoute: ReportsAttendanceRoute,
  ReportsFingerprintRoute: ReportsFingerprintRoute,
  TasksPermissionsRoute: TasksPermissionsRoute,
  TasksReportsRoute: TasksReportsRoute,
  TasksSetupRoute: TasksSetupRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
