ALTER TABLE public.loans
  ADD COLUMN IF NOT EXISTS emp_no text,
  ADD COLUMN IF NOT EXISTS national_id text,
  ADD COLUMN IF NOT EXISTS branch text DEFAULT 'شركة الحلول الخبيرة',
  ADD COLUMN IF NOT EXISTS department text,
  ADD COLUMN IF NOT EXISTS main_department text,
  ADD COLUMN IF NOT EXISTS sector text,
  ADD COLUMN IF NOT EXISTS path text,
  ADD COLUMN IF NOT EXISTS job_title text,
  ADD COLUMN IF NOT EXISTS nationality text,
  ADD COLUMN IF NOT EXISTS loan_type text NOT NULL DEFAULT 'سلفة شخصية',
  ADD COLUMN IF NOT EXISTS loan_name text,
  ADD COLUMN IF NOT EXISTS request_date date DEFAULT now(),
  ADD COLUMN IF NOT EXISTS entry_date date DEFAULT now(),
  ADD COLUMN IF NOT EXISTS first_installment_date date,
  ADD COLUMN IF NOT EXISTS deduction_method text DEFAULT 'تخصم شهريا',
  ADD COLUMN IF NOT EXISTS approved_amount numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS request_status text NOT NULL DEFAULT 'معتمدة',
  ADD COLUMN IF NOT EXISTS expense_account text,
  ADD COLUMN IF NOT EXISTS account_name text,
  ADD COLUMN IF NOT EXISTS stage text,
  ADD COLUMN IF NOT EXISTS posted boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS year integer,
  ADD COLUMN IF NOT EXISTS month integer,
  ADD COLUMN IF NOT EXISTS basic_salary numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS allowances numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_salary numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS attachment_url text;